import Link from 'next/link';
import {authClient,authConfigured} from '../../lib/supabase/server';
import {adminEmail,isAdmin} from '../../lib/admin';
import {calculate,enneagramLabel} from '../../lib/engine';
export const dynamic='force-dynamic';
export default async function Admin({searchParams}:{searchParams:Promise<{page?:string;error?:string}>}){
 const params=await searchParams;
 if(!authConfigured())return <main className="shell admin"><Link href="/">← 검사 사이트</Link><section className="card"><span className="sectionLabel">ADMIN</span><h1>관리자 데이터 연결 준비 중</h1><p>Supabase와 Google 로그인을 연결하면 관리자 계정으로 검사 결과를 확인할 수 있습니다.</p><p className="caption">관리자: {adminEmail}</p></section></main>;
 const client=await authClient();const {data:{user}}=await client.auth.getUser();
 if(!user)return <main className="shell admin"><Link href="/">← 검사 사이트</Link><section className="card"><span className="sectionLabel">ADMIN</span><h1>공동체를 이해하는 기록</h1>{params.error&&<p role="alert" className="notice">로그인을 완료하지 못했습니다. 다시 시도해 주세요.</p>}<a className="primary actionLink" href="/auth/login">관리자 계정으로 접속해주세요</a></section></main>;
 if(!isAdmin(user))return <main className="shell admin"><section className="card"><h1>관리자 권한이 없는 계정입니다</h1><p>지정된 Google 관리자 계정으로 다시 로그인해 주세요.</p><form method="post" action="/auth/logout"><button className="secondary">로그아웃</button></form></section></main>;
 const page=Math.max(1,Math.min(100000,Number.parseInt(params.page||'1',10)||1));const size=50;
 const {data,error,count}=await client.from('assessment_results').select('id,name,created_at,answers,engine_version,email_status',{count:'exact'}).order('created_at',{ascending:false}).order('id',{ascending:false}).range((page-1)*size,page*size-1);
 return <main className="shell admin"><header className="brandHeader"><Link href="/">CCLP · 사랑의교회 대학부</Link><form method="post" action="/auth/logout"><button className="textButton">로그아웃</button></form></header><section className="adminHero"><span className="sectionLabel">ADMIN DASHBOARD</span><h1>검사 결과 모아보기</h1><p>{adminEmail}</p><a className="secondary actionLink" href="/admin/export">표본 분석용 CSV 내려받기</a><div className="statCard"><span>저장된 검사</span><strong>{error?'—':count??0}</strong></div></section>{error?<p role="alert" className="notice">결과를 불러오지 못했습니다. 데이터베이스 연결과 조회 권한을 확인해 주세요.</p>:!data?.length?<section className="card"><h2>아직 저장된 결과가 없습니다</h2><p>검사자가 검사를 완료하고 중앙 저장에 성공하면 이곳에 표시됩니다. 기존 브라우저 저장 결과는 자동 수집되지 않습니다.</p></section>:<section className="adminRecords">{data.map(row=>{try{const r=calculate(row.answers);return <article className="card" key={row.id}><div className="recordHeading"><h2>{row.name}</h2><time>{new Date(row.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</time></div><p className="caption">메일 알림: {row.email_status==='accepted'?'발송 서비스 접수 완료':row.email_status==='unconfigured'?'메일 연결 필요':'발송 대기 또는 실패'}</p><p>{enneagramLabel(r)} · {r.topCharacters.join(' / ')}</p><div className="axisChips">{r.axes.map(x=><span key={x.name}>{x.name} <b>{x.score.toFixed(2)}</b></span>)}</div>{row.email_status!=='accepted'&&<form method="post" action="/admin/notifications"><input type="hidden" name="id" value={row.id}/><button className="textButton">메일 알림 다시 시도</button></form>}<Link className="recordLink" href={`/admin/results/${row.id}`}>상세 결과 읽기 →</Link></article>}catch{return <article className="card" key={row.id}>이 결과의 응답을 읽지 못했습니다.</article>}})}</section>}<nav className="pagination">{page>1&&<Link href={`/admin?page=${page-1}`}>← 이전</Link>}<span>{page}페이지</span>{count!==null&&page*size<count&&<Link href={`/admin?page=${page+1}`}>다음 →</Link>}</nav></main>;
}
