'use client';
import {FormEvent,useEffect,useState} from 'react';
import questions from '../lib/questions.json';
import {calculate,Result} from '../lib/engine';
import Report from './report';
const labels=['전혀 아니다','약간 아니다','약간 그렇다','매우 그렇다'];
const storageKey='cclp-results-v2.5';
type Saved={code:string;name:string;date:string;answers:number[]};
export default function Home(){
 const [screen,setScreen]=useState<'intro'|'test'|'result'>('intro');
 const [name,setName]=useState('');const [phone,setPhone]=useState('');const [consent,setConsent]=useState(false);
 const [answers,setAnswers]=useState<number[]>(Array(180).fill(-1));const [index,setIndex]=useState(0);const [result,setResult]=useState<Result|null>(null);
 const [records,setRecords]=useState<Saved[]>([]);const [code,setCode]=useState('');const [query,setQuery]=useState('');const [message,setMessage]=useState('');
 const [saveState,setSaveState]=useState('');const [saveDate,setSaveDate]=useState('');
 const answered=answers.filter(x=>x>=0).length;const progress=Math.round(answered/questions.length*100);
 useEffect(()=>{try{const data:unknown=JSON.parse(localStorage.getItem(storageKey)||'[]');if(!Array.isArray(data))throw new Error();const valid=data.filter((v):v is Saved=>Boolean(v)&&typeof v.code==='string'&&typeof v.name==='string'&&typeof v.date==='string'&&Array.isArray(v.answers)&&v.answers.length===180&&v.answers.every((x:unknown)=>typeof x==='number'&&Number.isInteger(x)&&x>=0&&x<=3));setRecords(valid);}catch{setMessage('이 브라우저의 저장된 결과를 읽지 못했습니다. 새 검사는 가능합니다.');}},[]);
 const changeScreen=(next:typeof screen)=>{setScreen(next);window.scrollTo(0,0)};
 const start=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const enteredName=String(form.get("name")||"").trim();if(!enteredName||!form.get("birthday")||!/^\d{4}$/.test(String(form.get("phone")||""))||!form.get("consent")){setMessage('이름, 생일, 전화번호 뒷자리 4개와 저장 안내 확인을 완료해 주세요.');return;}setName(enteredName);setMessage('');setPhone('');changeScreen('test')};
 const finish=()=>{try{const calculated=calculate(answers);const bytes=crypto.getRandomValues(new Uint8Array(8));const newCode='CCLP-'+Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();const date=new Date().toISOString();const saved={code:newCode,name:name.trim(),date,answers:[...answers]};setResult(calculated);setCode(newCode);setSaveDate(date);changeScreen('result');try{const next=[saved,...records];localStorage.setItem(storageKey,JSON.stringify(next));setRecords(next);setSaveState('이 기기·브라우저에 저장되었습니다. 결과 코드를 보관해 주세요.');}catch{setSaveState('브라우저 저장 공간을 사용할 수 없어 저장하지 못했습니다. 결과는 지금 읽을 수 있습니다. 인쇄/PDF로 보관해 주세요.');}}catch{setMessage('미응답 문항을 모두 선택해 주세요.');const missing=answers.findIndex(x=>x<0);if(missing>=0)setIndex(missing)}};
 const restore=(saved:Saved)=>{try{setResult(calculate(saved.answers));setAnswers([...saved.answers]);setName(saved.name);setCode(saved.code);setSaveDate(saved.date);setSaveState('이 기기·브라우저에 저장된 응답으로 결과를 다시 열었습니다.');setMessage('');changeScreen('result');}catch{setMessage('저장된 응답이 올바르지 않아 결과를 열지 못했습니다.')}};
 const find=(e:FormEvent)=>{e.preventDefault();const saved=records.find(x=>x.code===query.trim().toUpperCase());if(saved)restore(saved);else setMessage('이 브라우저에서 해당 결과 코드를 찾지 못했습니다. 다른 기기나 브라우저에서는 조회할 수 없습니다.')};
 const reset=()=>{setAnswers(Array(180).fill(-1));setIndex(0);setResult(null);setCode('');setName('');setConsent(false);setMessage('');changeScreen('intro')};
 const remove=()=>{try{const next=records.filter(x=>x.code!==code);localStorage.setItem(storageKey,JSON.stringify(next));setRecords(next);setSaveState('이 결과의 브라우저 저장본을 삭제했습니다. 현재 화면은 인쇄할 수 있지만 코드로 다시 조회할 수 없습니다.');}catch{setSaveState('저장본을 삭제하지 못했습니다. 브라우저의 사이트 데이터 설정에서 삭제할 수 있습니다.')}};
 if(screen==='intro')return <main className="shell"><section className="hero"><span className="pill">사랑의교회 대학6부</span><p className="eyebrow">CCLP · 공동체 리더십 프로파일</p><h1>나는 어떤 유형의<br/>공동체 리더인가?</h1><p>나의 성향과 강점을 이해하고, 공동체 안에서 함께 성장할 방향을 찾아보세요.</p><div className="info"><b>검사 안내</b><span>180문항 · 약 15–20분 · 0~3점 응답</span><p>평소의 모습을 떠올려 가장 가까운 답을 고르세요. 정답은 없습니다. 선택한 뒤 다음을 누르며, 이전 문항으로 돌아가 답을 바꿀 수 있습니다.</p><b>결과에서 만나는 네 가지 이야기</b><ol><li>애니어그램 프로파일</li><li>내면·관계·성장에 대한 심화해석</li><li>성경인물 TOP 3와 공동체 프로파일</li><li>4축·사역 영역·시너지와 성장 방향</li></ol></div><form onSubmit={start} className="entry"><label>이름<input name="name" required maxLength={40} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>생일<input name="birthday" required type="date" max={new Date().toLocaleDateString('en-CA')} defaultValue=""/></label><label>전화번호 뒷자리 4개<input name="phone" required inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))}/></label><p className="caption">구글 로그인 없이 검사할 수 있습니다. 이름과 응답은 결과 저장을 위해 이 브라우저에만 보관합니다. 생일과 전화번호 뒷자리는 시작 확인 후 보관하지 않으며, 결과 조회 암호로 사용하지 않습니다. 공유 기기에서는 결과 열람 후 저장본을 삭제해 주세요.</p><label className="check"><input name="consent" type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>브라우저 저장 안내를 확인했습니다.</label><button className="primary" type="submit">검사 시작하기</button></form>{message&&<p role="alert" className="notice">{message}</p>}<small>결과는 자기이해와 성장 대화를 위한 참고자료이며 진단이나 사역 배치 명령이 아닙니다.</small></section><section className="card"><h2>내 결과 다시 보기</h2><p>검사한 같은 기기·브라우저에서 결과 코드를 입력해 주세요.</p><form onSubmit={find} className="entry"><label>결과 코드<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="CCLP-…" autoCapitalize="characters" required/></label><button className="secondary">저장된 결과 열기</button></form><p className="caption">다른 기기 조회와 관리자 통합 조회는 지원하지 않습니다. 브라우저 데이터를 지우면 저장본도 삭제됩니다.</p></section></main>;
 if(screen==='test')return <main className="shell"><header className="top"><div><b>{index+1} / {questions.length}</b><span>{progress}% 완료</span></div></header><div className="bar" role="progressbar" aria-label="응답 진행률" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${progress}%`}}/></div><section className="question"><span className="qnum">문항 {index+1}</span><h1>{questions[index].text}</h1><p className="caption">답을 선택한 후 다음을 눌러 주세요.</p><div className="choices" role="group" aria-label="응답 선택">{labels.map((label,i)=><button type="button" key={label} aria-pressed={answers[index]===i} className={answers[index]===i?'selected':''} onClick={()=>setAnswers(prev=>prev.map((v,j)=>j===index?i:v))}><strong>{i}</strong><span>{label}</span>{answers[index]===i&&<span className="selectedLabel">선택됨</span>}</button>)}</div></section>{message&&<p role="alert">{message}</p>}<footer className="nav"><button disabled={index===0} onClick={()=>{setIndex(index-1);window.scrollTo(0,0)}}>이전</button>{index<179?<button className="done" disabled={answers[index]<0} onClick={()=>{setIndex(index+1);window.scrollTo(0,0)}}>다음</button>:<button className="done" disabled={answered!==180} onClick={finish}>결과 보기</button>}</footer></main>;
 if(!result)return null;
 return <main className="shell result"><Report result={result} name={name}/><section className="card resultStorage"><h2>결과 보관</h2><label>결과 코드<input aria-label="결과 코드" readOnly value={code}/></label><p>{saveState}</p><p className="caption">검사일 {new Date(saveDate).toLocaleDateString('ko-KR')} · 같은 기기·브라우저에서만 조회 가능</p><button className="primary" onClick={()=>window.print()}>결과 인쇄 / PDF 저장</button><p className="caption">인쇄 창에서 PDF로 저장을 선택하세요. PDF 저장이 어려워도 위 화면에서 전체 결과를 읽을 수 있습니다.</p><button className="secondary" onClick={()=>changeScreen('intro')}>시작 화면으로</button><button className="secondary" onClick={reset}>새 검사 시작하기</button><button className="textButton" onClick={remove}>이 결과의 브라우저 저장본 삭제</button></section></main>
}
