"use client";
import {useMemo,useState} from 'react'; import questions from '../lib/questions.json'; import {calculate,Result} from '../lib/engine';
const labels=['전혀 아니다','약간 아니다','약간 그렇다','매우 그렇다'];
const axisCopy:Record<string,string>={'공동체축':'질서와 신뢰를 세우고 공동체의 기반을 안정시키는 힘','사람축':'사람을 이해하고 격려하며 관계를 연결하는 힘','진리축':'원리와 말씀을 깊이 탐구하고 방향을 분별하는 힘','사명축':'비전을 행동과 열매로 연결하는 추진력'};
export default function Home(){const [screen,setScreen]=useState<'intro'|'test'|'result'>('intro');const [answers,setAnswers]=useState<number[]>(Array(180).fill(-1));const [index,setIndex]=useState(0);const [result,setResult]=useState<Result|null>(null);const answered=answers.filter(x=>x>=0).length;const progress=Math.round(answered/180*100);
 const choose=(v:number)=>{const n=[...answers];n[index]=v;setAnswers(n);if(index<179)setTimeout(()=>setIndex(index+1),120)};
 const finish=()=>{if(answered!==180)return;setResult(calculate(answers));setScreen('result');scrollTo(0,0)};
 const reset=()=>{setAnswers(Array(180).fill(-1));setIndex(0);setResult(null);setScreen('intro')};
 if(screen==='intro')return <main className='shell'><section className='hero'><span className='pill'>CCLP v2.5</span><h1>나의 리더십과<br/>공동체 강점을 발견하세요</h1><p>180개의 문항을 통해 애니어그램 성향, CCLP 4축, 성경인물 리더십 프로파일을 확인합니다.</p><div className='info'><b>검사 안내</b><span>약 15분 · 0~3점 응답 · 결과 즉시 확인</span></div><button className='primary' onClick={()=>setScreen('test')}>검사 시작하기</button><small>본 결과는 자기이해와 성장 대화를 위한 참고자료이며 의학적·심리학적 진단이 아닙니다.</small></section></main>;
 if(screen==='test')return <main className='shell'><header className='top'><button className='ghost' onClick={()=>setScreen('intro')}>←</button><div><b>{index+1} / 180</b><span>{progress}% 완료</span></div></header><div className='bar'><i style={{width:`${progress}%`}}/></div><section className='question'><span className='qnum'>QUESTION {index+1}</span><h2>{questions[index].text}</h2><div className='choices'>{labels.map((x,i)=><button key={x} className={answers[index]===i?'selected':''} onClick={()=>choose(i)}><strong>{i}</strong><span>{x}</span></button>)}</div></section><footer className='nav'><button disabled={index===0} onClick={()=>setIndex(index-1)}>이전</button>{index<179?<button onClick={()=>setIndex(index+1)}>다음</button>:<button className='done' disabled={answered!==180} onClick={finish}>결과 보기</button>}</footer></main>;
 if(!result)return null;return <main className='shell result'><section className='resultHero'><span className='pill'>MY CCLP PROFILE</span><h1>{result.topType}</h1><p>핵심 성향과 공동체 리더십 프로파일</p></section><section className='card'><h3>애니어그램 유형 분포</h3>{result.enneagram.map(x=><div className='score' key={x.name}><span>{x.name}</span><div><i style={{width:`${x.score}%`}}/></div><b>{x.score}</b></div>)}</section><section className='card'><h3>CCLP 4축</h3>{result.axes.map((x,i)=><article className='axis' key={x.name}><div><span className={`rank r${i}`}>{i+1}</span><b>{x.name}</b><strong>{x.score}</strong></div><div className='meter'><i style={{width:`${x.score}%`}}/></div><p>{axisCopy[x.name]}</p></article>)}</section><section className='card'><h3>성경인물 리더십 TOP 3</h3>{result.characters.slice(0,3).map((x,i)=><div className='character' key={x.name}><span>{i+1}</span><div><b>{x.name}</b><small>{x.score}점</small></div></div>)}</section><section className='card duo'><div><small>시너지 유형</small><b>{result.synergy}</b></div><div><small>주의가 필요한 유형</small><b>{result.caution}</b></div></section><section className='card summary'><h3>한눈에 보는 성장 방향</h3><p><b>{result.topAxis}</b>의 강점을 살리되, 상대적으로 낮은 <b>{result.lowAxis}</b>을 의식적으로 보완해 보세요. {result.topCharacters.join(' · ')}의 조합은 현재 공동체 안에서 드러나는 리더십 자원의 방향을 보여 줍니다.</p></section><button className='primary' onClick={()=>window.print()}>결과 저장 / 인쇄</button><button className='secondary' onClick={reset}>다시 검사하기</button></main>}
