import {Result,Score} from '../lib/engine';
import {types,characters,axisCopy} from '../lib/interpretation';
function Scores({items}:{items:Score[]}){return <div>{items.map(x=><div className="score" key={x.name}><span>{x.name}</span><div><i style={{width:`${x.score}%`}}/></div><b>{x.score.toFixed(2)}</b></div>)}</div>}
function Copy({title,children}:{title:string;children:React.ReactNode}){return <article className="copy"><h3>{title}</h3><p>{children}</p></article>}
export default function Report({result:r,name}:{result:Result;name:string}){
 const type=types[r.topType];const top=characters[r.topCharacters[0]];
 const uncertain=r.flat||r.tiedTypes.length>1||r.tiedCharacters.length>1;
 return <>
 <section className="resultHero"><span className="pill">사랑의교회 대학6부</span><h1>{name}님의<br/>공동체 리더십 프로파일</h1><p>나를 이해하고 함께 성장하기 위한 네 가지 이야기</p></section>
 {uncertain&&<aside className="notice">{r.flat?'모든 응답이 같아 개인의 차이를 충분히 구분하기 어렵습니다. ':''}{r.tiedTypes.length>1?`핵심유형 동점: ${r.tiedTypes.join(' · ')}. `:''}{r.tiedCharacters.length>1?`성경인물 최고점 동점: ${r.tiedCharacters.join(' · ')}. `:''}동점은 같은 순위로 표시합니다. 아래 개별 유형 설명은 비교를 위한 참고이며 한 유형으로 확정하지 않습니다.</aside>}
 <section className="card reportSection" id="profile"><span className="sectionLabel">01 · 애니어그램 프로파일</span><h2>{uncertain?'상위 성향 살펴보기':`${r.topType} · ${type.title}`}</h2><Scores items={r.enneagram}/><p className="caption">각 유형의 원점수를 최고 원점수 대비 상대점수로 표시합니다. 확률이나 구성 비율이 아닙니다.</p><span className="authored">웹용 새 작성 해설</span>
 <Copy title="핵심동기">{type.motivation}</Copy><Copy title="핵심 두려움">{type.fear}을 염려할 수 있습니다.</Copy>
 <Copy title="날개와 영향유형">날개 후보는 인접한 {r.wings.map(x=>`${x.name} (${x.score.toFixed(2)})`).join(' · ')}입니다. {r.wings[0].raw===r.wings[1].raw?'두 후보가 동점이므로 하나로 정하지 않습니다.':`${r.wings[0].name}의 점수가 더 높아 먼저 비교할 수 있습니다.`} 영향유형 후보는 {r.influences.map(x=>x.name).join(' · ')}이며, 상위 응답 성향을 함께 살펴보는 표시입니다.</Copy>
 <Copy title="통합·퇴행의 참고 방향">전통적인 유형 해석에서는 성장 방향을 {type.integration}유형, 스트레스 방향을 {type.regression}유형과 연결합니다. 이 연결은 응답으로 측정한 상태가 아니므로 실제 경험과 함께 살펴보세요.</Copy><Copy title="한 줄 요약">{type.strength} 이 강점을 얼마나 자주 쓰는지 자신의 경험에서 확인해 보세요.</Copy></section>
 <section className="card reportSection" id="depth"><span className="sectionLabel">02 · 애니어그램 심화해석</span><h2>내면과 관계를 이해하기</h2><span className="authored">웹용 새 작성 해설</span><Copy title="내면동기">{type.inner}</Copy><Copy title="강점">{type.strength}</Copy><Copy title="관계 특징">{type.relationship}</Copy><Copy title="스트레스 패턴">{type.stress}</Copy><Copy title="성장 과제">{type.growth}</Copy><Copy title="성장 방향">{type.direction}</Copy><Copy title="종합해석">{r.topType}의 설명 가운데 실제 경험과 맞는 부분부터 선택해 보세요. {r.influences.map(x=>x.name).join(' · ')}의 성향도 함께 비교하면 자신을 한 가지 모습으로만 해석하는 일을 줄일 수 있습니다.</Copy></section>
 <section className="card reportSection" id="community"><span className="sectionLabel">03 · CCLP 공동체 프로파일</span><h2>나는 어떤 공동체 리더인가?</h2><span className="authored">웹용 새 작성 해설</span>{r.characters.slice(0,3).map(x=>{const c=characters[x.name];return <article className="characterCopy" key={x.name}><h3>{r.characters.filter(item=>item.rank===x.rank).length>1?"공동 ":""}{x.rank}위 · {x.name} <small>{x.score.toFixed(2)}점</small></h3><p>{c.summary}이 응답에서 드러납니다.</p><Copy title="공동체에 더하는 유익">{c.benefit}</Copy><Copy title="조심할 수 있는 패턴">{c.caution}</Copy></article>})}
 {r.evidence.length>0&&<article className="copy"><h3>원본의 문항별 공개 표현</h3><span className="sourceLabel">원본 문구 · 높은 응답의 역량 문항에서 선택</span>{r.evidence.map(x=><blockquote key={x}>{x}</blockquote>)}</article>}
 <Copy title="개인화된 권면">{top.counsel} {r.topCharacters.join(' · ')}의 조합을 살펴보면 한 가지 역할보다 여러 자원을 함께 쓰는 길을 생각할 수 있습니다. 상대적으로 높은 {r.topAxis}의 자원을 활용하고, {r.lowAxis}은 부족함을 단정하기보다 도움과 연습을 더할 영역으로 살펴보세요. {axisCopy[r.lowAxis].practice}</Copy></section>
 <section className="card reportSection" id="ministry"><span className="sectionLabel">04 · CCLP 사역 프로파일</span><h2>함께 섬기며 성장하기</h2><Scores items={r.axes}/><p className="caption">4축과 성경인물 점수는 원점수 ÷ 최대가능점수의 절대환산에 원본 v2.5 고정 보정식을 적용한 표시점수입니다. 0점 응답도 보정 후 10점으로 표시됩니다. 최고값을 자동으로 100점으로 만들지 않습니다.</p><span className="authored">웹용 새 작성 해설</span>{r.axes.map(x=><Copy key={x.name} title={`${x.name} · ${x.score.toFixed(2)}점`}>{axisCopy[x.name].meaning} {axisCopy[x.name].practice}</Copy>)}<Copy title="책임을 맡을 때의 장점">{top.benefit} {axisCopy[r.topAxis].meaning}</Copy><Copy title="빛이 나는 사역 영역">{axisCopy[r.topAxis].service}에서 자신의 자원을 시험해 볼 수 있습니다. 점수는 배치 명령이 아니며 관심, 실제 경험, 공동체의 필요를 함께 고려하세요.</Copy>
 <article className="copy"><h3>시너지 유형 · {r.synergy}</h3><span className="sourceLabel">원본 관계 설명</span><blockquote>{r.synergyReason}</blockquote><span className="authored">웹용 새 작성 연결문</span><p>서로의 역할과 기대를 합의하고 작은 일을 함께 해 보며 이 조합이 실제 관계에서 어떻게 도움이 되는지 확인해 보세요.</p></article>
 <article className="copy"><h3>주의 유형 · {r.caution}</h3><span className="sourceLabel">원본 관계 설명</span><blockquote>{r.cautionReason}</blockquote><span className="authored">웹용 새 작성 연결문</span><p>왜 충돌할 수 있는가: 중요하게 여기는 기준과 진행 방식이 다를 수 있기 때문입니다. 이는 상대의 문제를 뜻하지 않습니다. 시작 전에 속도, 결정 방법, 도움을 원하는 방식을 함께 이야기해 보세요.</p></article>
 <Copy title="공동체 안에서 살필 점">{top.caution} 도움을 요청하고 다른 유형의 강점을 듣는 시간을 마련해 보세요.</Copy><Copy title="추천말씀과 묵상 방향">{top.verse} · {top.verseTheme}. 본문 전체의 맥락을 읽고 현재의 상황과 연결해 묵상해 보세요. 이 추천은 웹용으로 새로 작성했습니다.</Copy><Copy title="성장 키워드">{r.topAxis} 활용 · {r.lowAxis} 연습 · 위임 · 포용</Copy><Copy title="마지막 격려">{name}님의 자원은 공동체 안에서 다른 사람의 강점과 만날 때 더 넓게 쓰일 수 있습니다. 이번 주에는 {axisCopy[r.lowAxis].practice} 점수의 크기보다 함께 성장하는 작은 실천을 소중히 여겨 주세요.</Copy></section>
 <p className="caption">점수·문항·관계 설명은 CCLP v2.5 원본을 반영했습니다. 원본 인용에는 별도 표기를 붙였으며 나머지 상세 해설은 웹용으로 새로 작성했습니다. 결과는 자기이해와 성장 대화를 위한 참고자료이며 진단이나 사역 배치 기준이 아닙니다.</p>
 </>
}
